### ISSUE TITLE
Problem persisting all the samples into InfluxDB with JMeter-InfluxDB-Writer 1.1

### ISSUE THREAD

**Issue by ankitjn121** [NovaTecConsulting/JMeter-InfluxDB-Writer#3]
Hi,

I have setup Jmeter with InfluxDB and Grafana, and adding "JMeter-InfluxDB-Writer 1.1" as mentioned in the documentation link "https://grafana.net/dashboards/1152".

With this, I am seeing some of the samples are missing (shows 8/10 samples for some of the api's) when queried in the InfluxDB although Jmeter Summary report shows 10/10 samples run for all the api's.

Also attaching my infuxDB.conf for any inputs. Please help
[influxdb.zip](https://github.com/NovaTecConsulting/JMeter-InfluxDB-Writer/files/836615/influxdb.zip)

**Comment by gokhansengun** [comment]
@ankitjn121 I have a similar issue and it is due to the way InfluxDB works. If you are running virtual users from multiple threads then it is likely that two threads write the sample to InfluxDB at the same time. InfluxDB inserts the value point for the first thread and updates it for the second. 

This Plugin is keeping time in Milliseconds, if the samples happening in the very same milliseconds, one of them is lost.

Best solution is to add another tag to the Point adding the Node-Id and the Thread-Id so that different threads to produce different data points and different nodes to produce different data points.

I will look into adding this to this plugin if time permits.

**Comment by gokhansengun** [comment]
I have attempted to fix this issue with #5. I am aware that it is not the best solution but it just works.

**Comment by AlexanderWert** [comment]
Resolved with #5

**Comment by ankitjn121** [comment]
Thanks all! I made some changes to the plugin and recompiled. The issue was fixed with that.
