### ISSUE TITLE
Better multiple node support is needed

### ISSUE THREAD

**Issue by gokhansengun** [NovaTecConsulting/JMeter-InfluxDB-Writer#6]
Running multiple JMeter nodes to create high volumes of traffic, due to issue #3 some measurements are overriden in InfluxDB. In addition to that the total number of users and etc could not be shown.

I will attempt to add nodeName configuration parameter just like testName. I think it is better not to retrieve from the running node and allowing user to enter or inject values because there could be some complex configurations (like running multiple JMeter instances in the same host).

**Comment by gokhansengun** [comment]
Just sent the PR #7 for this. Please have a look.

**Comment by AlexanderWert** [comment]
#7 resolved this issue

**Comment by hrgsurya** [comment]
Hi,

I am using above solution ( out-of-box from NovaTec-APM for the dashboard after downloading the jar ) I am able to see nice graphs but its showing only 5 active users instead of 15 users ( as I am running three different scripts each with 5 users. Please note that I have used Backendlisteners in each script. Please find the screenshot attached for the Backendlisteners and let me know if I am missing anything.
Appreciate ypur quick respone
Thnx

**Comment by hrgsurya** [comment]
Hi Alex, any suggestion on the above issue ?
 Appreciate your quick help on this ...

Thanks in advance..
